package Login;

import ForgotPassword.f2;
import Realsignuppage.Signuppp;
import Signup.Sign;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;
        
public class window extends javax.swing.JFrame {

    /**
     * Creates new form window
     */
    public window() {
        initComponents();
        
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        Checkbox = new javax.swing.JCheckBox();
        Aquasynclab = new javax.swing.JLabel();
        Aquasynclab2 = new javax.swing.JLabel();
        Aquasynclab3 = new javax.swing.JLabel();
        Aquasynclab4 = new javax.swing.JLabel();
        Aquasynclab5 = new javax.swing.JLabel();
        AQUASYNC = new javax.swing.JLabel();
        USERNAME = new javax.swing.JTextField();
        PASS = new javax.swing.JPasswordField();
        Below = new javax.swing.JLabel();
        Forog = new javax.swing.JButton();
        Paslab = new javax.swing.JLabel();
        Signup = new javax.swing.JButton();
        Uselab = new javax.swing.JLabel();
        Login1 = new javax.swing.JButton();
        Donthave = new javax.swing.JLabel();
        win = new javax.swing.JLabel();

        jLabel4.setFont(new java.awt.Font("Garamond", 0, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Forgot Password?");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Checkbox.setBackground(new java.awt.Color(255, 255, 255));
        Checkbox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Checkbox.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/eye.png"))); // NOI18N
        Checkbox.setIconTextGap(1);
        Checkbox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CheckboxMouseClicked(evt);
            }
        });
        getContentPane().add(Checkbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 380, 40, 30));

        Aquasynclab.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 18)); // NOI18N
        Aquasynclab.setForeground(new java.awt.Color(255, 255, 255));
        Aquasynclab.setText("AquaSync");
        getContentPane().add(Aquasynclab, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 150, 40));

        Aquasynclab2.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 18)); // NOI18N
        Aquasynclab2.setForeground(new java.awt.Color(255, 255, 255));
        Aquasynclab2.setText("app   designed   to   help   you    track");
        getContentPane().add(Aquasynclab2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 350, 40));

        Aquasynclab3.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 18)); // NOI18N
        Aquasynclab3.setForeground(new java.awt.Color(255, 255, 255));
        Aquasynclab3.setText("water consumption, reduce water waste,");
        getContentPane().add(Aquasynclab3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, 330, 40));

        Aquasynclab4.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 18)); // NOI18N
        Aquasynclab4.setForeground(new java.awt.Color(255, 255, 255));
        Aquasynclab4.setText("and     promote    sustainable    habits.");
        getContentPane().add(Aquasynclab4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, 330, 40));

        Aquasynclab5.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 18)); // NOI18N
        Aquasynclab5.setForeground(new java.awt.Color(255, 255, 255));
        Aquasynclab5.setText("is a water usage monitoring");
        getContentPane().add(Aquasynclab5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 230, 40));

        AQUASYNC.setFont(new java.awt.Font("Cinzel SemiBold", 0, 40)); // NOI18N
        AQUASYNC.setForeground(new java.awt.Color(255, 255, 255));
        AQUASYNC.setText("AquaSync");
        getContentPane().add(AQUASYNC, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, 220, 50));

        USERNAME.setFont(new java.awt.Font("Nostalgic Whispers", 0, 24)); // NOI18N
        USERNAME.setBorder(null);
        USERNAME.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        USERNAME.setOpaque(true);
        USERNAME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                USERNAMEActionPerformed(evt);
            }
        });
        getContentPane().add(USERNAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 280, 290, 40));

        PASS.setFont(new java.awt.Font("Nostalgic Whispers", 0, 24)); // NOI18N
        PASS.setBorder(null);
        PASS.setOpaque(true);
        PASS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PASSActionPerformed(evt);
            }
        });
        getContentPane().add(PASS, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 380, 250, 30));

        Below.setFont(new java.awt.Font("Cinzel", 0, 18)); // NOI18N
        Below.setForeground(new java.awt.Color(255, 255, 255));
        Below.setText("Water. personalized.");
        getContentPane().add(Below, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 160, 220, 30));

        Forog.setBackground(new java.awt.Color(42, 100, 145));
        Forog.setFont(new java.awt.Font("Garamond", 0, 22)); // NOI18N
        Forog.setForeground(new java.awt.Color(255, 255, 255));
        Forog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/Untitled design.png"))); // NOI18N
        Forog.setText("Forgot Password");
        Forog.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 255, 255), new java.awt.Color(204, 255, 255), new java.awt.Color(51, 255, 255), new java.awt.Color(102, 255, 255)));
        Forog.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Forog.setFocusPainted(false);
        Forog.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Forog.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/input.png"))); // NOI18N
        Forog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ForogMouseClicked(evt);
            }
        });
        Forog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ForogActionPerformed(evt);
            }
        });
        getContentPane().add(Forog, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 430, 170, 30));

        Paslab.setFont(new java.awt.Font("Sarasvati", 1, 18)); // NOI18N
        Paslab.setForeground(new java.awt.Color(255, 255, 255));
        Paslab.setText("Password");
        getContentPane().add(Paslab, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 340, -1, 30));

        Signup.setBackground(new java.awt.Color(0, 0, 204));
        Signup.setFont(new java.awt.Font("Garamond", 0, 13)); // NOI18N
        Signup.setForeground(new java.awt.Color(255, 255, 255));
        Signup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/Untitled design.png"))); // NOI18N
        Signup.setText("Sign up");
        Signup.setBorder(null);
        Signup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Signup.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Signup.setOpaque(true);
        Signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignupActionPerformed(evt);
            }
        });
        getContentPane().add(Signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 570, 70, 20));

        Uselab.setFont(new java.awt.Font("Sarasvati", 1, 18)); // NOI18N
        Uselab.setForeground(new java.awt.Color(255, 255, 255));
        Uselab.setText("Username");
        getContentPane().add(Uselab, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 240, 90, 30));

        Login1.setBackground(new java.awt.Color(22, 93, 148));
        Login1.setFont(new java.awt.Font("Garamond", 0, 22)); // NOI18N
        Login1.setForeground(new java.awt.Color(255, 255, 255));
        Login1.setText("Login");
        Login1.setBorder(null);
        Login1.setBorderPainted(false);
        Login1.setContentAreaFilled(false);
        Login1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Login1.setFocusPainted(false);
        Login1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Login1.setPreferredSize(new java.awt.Dimension(1000, 3213));
        Login1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/input.png"))); // NOI18N
        Login1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login1ActionPerformed(evt);
            }
        });
        getContentPane().add(Login1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 480, 190, 43));

        Donthave.setFont(new java.awt.Font("Garamond", 0, 17)); // NOI18N
        Donthave.setForeground(new java.awt.Color(255, 255, 255));
        Donthave.setText("Dont have account?");
        getContentPane().add(Donthave, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 570, 130, 20));

        win.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/Aquak.png"))); // NOI18N
        win.setText("jLabel4");
        getContentPane().add(win, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 700));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void USERNAMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_USERNAMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_USERNAMEActionPerformed

    private void PASSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PASSActionPerformed
        
    }//GEN-LAST:event_PASSActionPerformed

    private void ForogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ForogActionPerformed
        
    }//GEN-LAST:event_ForogActionPerformed

    private void SignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignupActionPerformed
    Signuppp signupWindow = new Signuppp();
    signupWindow.setVisible(true);

    // Close the current window
    this.dispose();
    }//GEN-LAST:event_SignupActionPerformed

    private void Login1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login1ActionPerformed
    String enteredUsername = USERNAME.getText().trim();
    String enteredPassword = new String(PASS.getPassword()).trim();

    // Debug: Print values to check if fields are empty
    System.out.println("Entered Username: " + enteredUsername);
    System.out.println("Entered Password: " + enteredPassword);

    // Check for empty fields
    if (enteredUsername.isEmpty() || enteredPassword.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please fill up empty fields!","ERROR",JOptionPane.ERROR_MESSAGE);
        return; // Exit method if any field is empty
    }

    // Read from the text file and validate credentials
    try (BufferedReader reader = new BufferedReader(new FileReader("userDatabase.txt"))) {
        String line;
        boolean loginSuccessful = false;

        while ((line = reader.readLine()) != null) {
            String[] userData = line.split(",");
            String username = userData[0].trim();
            String password = userData[1].trim();

            // Check if the entered credentials match any line in the file
            if (enteredUsername.equals(username) && enteredPassword.equals(password)) {
                loginSuccessful = true;
                break;
            }
        }

        if (loginSuccessful) {
            JOptionPane.showMessageDialog(this, "Login successful!");
            // Open the third window here
            Sign thirdWindow = new Sign();
            thirdWindow.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Invalid username or password.","ERROR",JOptionPane.ERROR_MESSAGE);
        }
    } catch (IOException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error reading user data.","ERROR",JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_Login1ActionPerformed

    private void CheckboxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckboxMouseClicked
        if (Checkbox.isSelected()){
             PASS.setEchoChar((char )0);
        } else {
            PASS.setEchoChar('•');
        }
    
    }//GEN-LAST:event_CheckboxMouseClicked

    private void ForogMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ForogMouseClicked
    f2 loginWindow = new f2();
    loginWindow.setVisible(true);

    // Close the Signuppp window
    this.dispose();
    }//GEN-LAST:event_ForogMouseClicked

    /**
     * @param args the command line arguments
     */
    protected static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new window().setVisible(true);
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AQUASYNC;
    private javax.swing.JLabel Aquasynclab;
    private javax.swing.JLabel Aquasynclab2;
    private javax.swing.JLabel Aquasynclab3;
    private javax.swing.JLabel Aquasynclab4;
    private javax.swing.JLabel Aquasynclab5;
    private javax.swing.JLabel Below;
    private javax.swing.JCheckBox Checkbox;
    private javax.swing.JLabel Donthave;
    private javax.swing.JButton Forog;
    private javax.swing.JButton Login1;
    private javax.swing.JPasswordField PASS;
    private javax.swing.JLabel Paslab;
    private javax.swing.JButton Signup;
    private javax.swing.JTextField USERNAME;
    private javax.swing.JLabel Uselab;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel win;
    // End of variables declaration//GEN-END:variables
}
